language: python
python:
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
install: pip install -r test/requirements.txt --use-mirrors
script: python test/alltests.py
before_script:
  - "psql -c 'create database webpy;' -U postgres"
